title: 'Students in Mental Health Research'
default_lang: en
author:
  name: 'Jeffrey He'
  email: jhe1120@gmail.com
  copyright: 'Copyright 2018 SMHR. All Rights Reserved.'
taxonomies:
  - category
  - tag
  - featured
metadata:
  description: 'A student run organization dedicated to building a community of student learners devoted to raising awareness about global mental health issues.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
routes:
  /something/else: /blog/sample-3
  /another/one/here: /blog/sample-3
  '/new/*': '/blog/*'
blog:
  route: /blog
logo: logo.png
header:
  title: 'Students in Mental Health Research'
  description: 'Students in Mental Health Research: A Global Mental Health Initiative (SMHR) is a student run organization dedicated to building a community of student learners devoted to raising awareness about global mental health issues.'
  background: background.jpg
  buttons:
    -
      text: 'Learn More'
      url: about
      class: 'button radius'
social:
  -
    url: 'https://www.facebook.com/harvardcollegementalhealthresearchgroup/'
    icon: facebook
  -
    url: 'mailto:harvardmentalhealthresearch@gmail.com'
    icon: envelope
  -
    url: www.hcs.harvard.edu/~hcht/
    icon: info-circle
footer:
  widget:
    title: 'Students in Mental Health Research'
    description: 'A student run organization dedicated to building a community of student learners devoted to raising awareness about global mental health issues.'
    link: null
copyright: '© 2018 Students in Mental Health Research. All Rights Reserved. By <a href="http://rescuethemes.com/">Rescue Themes</a> and <a href="http://www.getgrav.org">Grav</a>.'
