title: 'Harvard College Healing Thoughts'
default_lang: en
author:
  name: 'Jeffrey He'
  email: jhe1120@gmail.com
  copyright: 'Copyright 2017 HCHT. All Rights Reserved.'
taxonomies:
  - category
  - tag
  - featured
metadata:
  description: 'A student run organization dedicated to building a community of student learners devoted to raising awareness about global mental health issues.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
routes:
  /something/else: /blog/sample-3
  /another/one/here: /blog/sample-3
  '/new/*': '/blog/*'
blog:
  route: /blog
logo: logo.png
header:
  title: 'Healing Thoughts'
  description: 'Harvard College Healing Thoughts: A Global Mental Health Initiative (HCHT) is a student run organization dedicated to building a community of student learners devoted to raising awareness about global mental health issues.'
  background: background.jpg
  buttons:
    -
      text: 'Learn More'
      url: 'about'
      class: 'button radius'
social:
  -
    url: 'https://twitter.com/'
    icon: twitter
  -
    url: '#'
    icon: facebook
  -
    url: 'http://www.vimeo.com'
    icon: vimeo-square
  -
    url: 'http://www.pinterest.com'
    icon: pinterest
footer:
  widget:
    title: 'Harvard College Healing Thoughts'
    description: 'A student run organization dedicated to building a community of student learners devoted to raising awareness about global mental health issues.'
    link: null
copyright: '© 2017 Healing Thoughts. All Rights Reserved. By <a href="http://rescuethemes.com/">Rescue Themes</a> and <a href="http://www.getgrav.org">Grav</a>.'
